### ISSUE TITLE
功能建议:使用 = 而不是 - 连接类名

### ISSUE THREAD

**Issue by cereschen** [macheteHot/css-generator-plugin#6]
before:
 w-20  .w-20{width:20px}
after:
 w=20     .w\=20{width:20px}

why?
为了可以和tailwind或者其他原子类css框架兼容 而且更加符合语义 让 css-generator-plugin 更加专注于动态的样式
或者可以提供选项以启用 自定义连接符

**Comment by macheteHot** [comment]
感谢您的提醒 确实可能造成 错误扫描其他原子类框架问题
改动将会较大 也许会在以后版本发布
